# fly.toml app configuration file generated for young-star-9552 on 2023-09-23T22:17:31+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "young-star-9552"
primary_region = "mad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
